# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - NetCoreExampleApi/*

pool:
  vmImage: 'ubuntu-latest'


variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet publish
  displayName: 'dotnet build and publish'
  workingDirectory: './NetCoreExampleApi'
- task: CopyFiles@2
  inputs:
    contents: '/home/vsts/work/1/s/NetCoreExampleApi/bin/Debug/net6.0/publish/**'
    targetFolder: $(Build.ArtifactStagingDirectory)

- script: |
    ls
  displayName: check location

- task: PublishBuildArtifacts@1

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(51a91c39-8f83-4f4d-ac7b-a9b943350929)'
    appType: 'webAppLinux'
    WebAppName: 'azure-demo-web-app-linux'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'
    RuntimeStack: 'DOTNETCORE|6.0'